import type { ActivityEvent } from "./types";

/**
 * NEEDS-ENDPOINT: GET /api/v1/activity?project_id=
 *
 * Newest first. Only events that changed the data or the results are recorded,
 * because the log exists to explain why today's numbers differ from yesterday's.
 */
export const ACTIVITY: ActivityEvent[] = [
  {
    event_id: "act_0119",
    kind: "dataset_updated",
    project_id: "prj-abc",
    project_name: "Sales 2026",
    organisation: "PT ABC Distribution",
    at: "2026-09-17T14:02:00+07:00",
    actor: "Sari Wijaya",
    summary: "Merged sales_2026_w38.csv into the dataset",
    details: [
      "1,284 rows added",
      "316 overlapping rows replaced",
      "152,639 existing rows kept",
      "Coverage extended to 16 Sep 2026",
    ],
  },
  {
    event_id: "act_0118",
    kind: "recommendations_refreshed",
    project_id: "prj-abc",
    project_name: "Sales 2026",
    organisation: "PT ABC Distribution",
    at: "2026-09-17T13:44:00+07:00",
    actor: "System",
    summary: "Inventory recommendations recalculated",
    details: ["5 items need an order", "2 moved into stockout risk"],
  },
  {
    event_id: "act_0117",
    kind: "forecast_generated",
    project_id: "prj-abc",
    project_name: "Sales 2026",
    organisation: "PT ABC Distribution",
    at: "2026-09-17T13:42:00+07:00",
    actor: "System",
    summary: "Forecast generated over a 30-day horizon",
    details: ["417 series forecast", "WAPE 11.4% against 19.7% for the baseline"],
  },
  {
    event_id: "act_0116",
    kind: "mapping_confirmed",
    project_id: "prj-abc",
    project_name: "Sales 2026",
    organisation: "PT ABC Distribution",
    at: "2026-09-17T13:30:00+07:00",
    actor: "Sari Wijaya",
    summary: "Column mapping confirmed",
    details: ["qty_out kept as Demand Quantity", "No columns changed"],
  },
  {
    event_id: "act_0115",
    kind: "health_changed",
    project_id: "prj-abc",
    project_name: "Sales 2026",
    organisation: "PT ABC Distribution",
    at: "2026-09-17T13:28:00+07:00",
    actor: "System",
    summary: "Data health scored 82 of 100",
    details: ["193 duplicates aggregated", "38 series show censored demand"],
  },
  {
    event_id: "act_0114",
    kind: "dataset_uploaded",
    project_id: "prj-abc",
    project_name: "Sales 2026",
    organisation: "PT ABC Distribution",
    at: "2026-09-17T06:12:00+07:00",
    actor: "Sari Wijaya",
    summary: "Uploaded sales_2026.csv",
    details: ["154,239 rows", "428 series detected", "Matched the Accurate Online preset"],
  },
  {
    event_id: "act_0113",
    kind: "dataset_uploaded",
    project_id: "prj-nus",
    project_name: "Produksi Q3",
    organisation: "PT Nusantara Boga",
    at: "2026-09-16T09:30:00+07:00",
    actor: "Nadia Putri",
    summary: "Uploaded pos_export_agustus.csv",
    details: ["62,104 rows", "192 series detected", "Mapping needs review"],
  },
  {
    event_id: "act_0112",
    kind: "dataset_updated",
    project_id: "prj-abc",
    project_name: "Sales 2026",
    organisation: "PT ABC Distribution",
    at: "2026-09-10T11:20:00+07:00",
    actor: "Sari Wijaya",
    summary: "Merged sales_2026_w37.csv into the dataset",
    details: ["1,197 rows added", "204 overlapping rows replaced"],
  },
];
