import type { OverviewResponse, ValueSimulation } from "./types";
import { OVERVIEW_DAILY } from "./series.ts";

/** NEEDS-ENDPOINT: GET /api/v1/overview/{dataset_id} */
export const OVERVIEW: OverviewResponse = {
  dataset_id: "ds_8f21c4",
  generated_at: "2026-09-17T13:42:00+07:00",
  kpis: [
    {
      key: "demand_forecast",
      label: "Demand Forecast",
      value: 58204,
      unavailable_reason: null,
      unit: "units",
      context: "Next 30 days · 417 series",
      comparison: { delta_percent: 1.9, direction: "up", label: "vs previous 30 days" },
      accent: "demand",
      href: "/projects/prj-abc/dashboard/demand",
    },
    {
      key: "revenue_forecast",
      label: "Revenue Forecast",
      value: 4862400000,
      unavailable_reason: null,
      unit: "idr",
      context: "Next 30 days · at current unit prices",
      comparison: { delta_percent: 2.4, direction: "up", label: "vs previous 30 days" },
      accent: "forecast",
      href: "/projects/prj-abc/dashboard/demand",
    },
    {
      key: "inventory_value",
      label: "Inventory Value",
      // Deliberately unavailable: the dataset carries selling price but no unit
      // cost, so a rupiah stock valuation cannot be produced honestly.
      value: null,
      unavailable_reason: "Unit cost is not present in this dataset. Stock is tracked in units.",
      unit: "idr",
      context: "Current stock position",
      comparison: null,
      accent: "inventory",
      href: "/projects/prj-abc/dashboard/supply-chain",
    },
    {
      key: "stockout_risk",
      label: "Stockout Risk",
      value: 5,
      unavailable_reason: null,
      unit: "count",
      context: "SKUs below cover · of 417 forecastable",
      comparison: { delta_percent: 2, direction: "up", label: "vs last run" },
      accent: "risk",
      href: "/projects/prj-abc/dashboard/supply-chain?risk=attention",
    },
  ],
  demand_chart: {
    label: "Actual vs forecast demand",
    cutoff_index: 119,
    points: OVERVIEW_DAILY,
    historical_range: { from: "2026-05-20", to: "2026-09-16" },
    forecast_range: { from: "2026-09-17", to: "2026-10-16" },
    unit: "units",
  },
  inventory: {
    bands: [
      { risk: "critical", label: "Stockout risk", series_count: 2 },
      { risk: "at_risk", label: "At risk", series_count: 3 },
      { risk: "watch", label: "Watch", series_count: 2 },
      { risk: "healthy", label: "Healthy", series_count: 11 },
    ],
    total_series: 18,
    inventory_value: {
      available: false,
      reason: "Unit cost is not present in this dataset.",
    },
    median_coverage_days: 34,
    narrative:
      "Cover is adequate across most of the portfolio. Five items sit below their replenishment lead time and need a decision this week.",
  },
  priority_actions: [
    {
      rank: 1,
      series_id: "KCG-200__SBY-02",
      item_name: "Kacang Garuda 200g",
      location: "Surabaya",
      headline: "Order 5,000 units",
      reason: "7 days of cover against a 14-day lead time. Demand is erratic and trending up.",
      risk: "critical",
      metric_label: "Days until stockout",
      metric_value: 7,
      metric_unit: "days",
      href: "/projects/prj-abc/dashboard/supply-chain?series=KCG-200__SBY-02",
    },
    {
      rank: 2,
      series_id: "MNK-2L__MDN-01",
      item_name: "Minyak Sania 2L",
      location: "Medan",
      headline: "Order 8,000 units",
      reason: "23 days of cover against a 45-day import lead time. Largest exposure by volume.",
      risk: "critical",
      metric_label: "Days until stockout",
      metric_value: 23,
      metric_unit: "days",
      href: "/projects/prj-abc/dashboard/supply-chain?series=MNK-2L__MDN-01",
    },
    {
      rank: 3,
      series_id: "SBN-500__SMG-01",
      item_name: "Sabun Nuvo 500ml",
      location: "Semarang",
      headline: "Order 100 units",
      reason: "Lumpy demand with 12 days of cover. Order size is set by the 50-unit minimum.",
      risk: "at_risk",
      metric_label: "Days until stockout",
      metric_value: 12,
      metric_unit: "days",
      href: "/projects/prj-abc/dashboard/supply-chain?series=SBN-500__SMG-01",
    },
    {
      rank: 4,
      series_id: "SAR-60__MDN-01",
      item_name: "Sarden ABC 155g",
      location: "Medan",
      headline: "Order 200 units",
      reason: "Lumpy demand, 18 days of cover against a 21-day lead time.",
      risk: "at_risk",
      metric_label: "Days until stockout",
      metric_value: 18,
      metric_unit: "days",
      href: "/projects/prj-abc/dashboard/supply-chain?series=SAR-60__MDN-01",
    },
    {
      rank: 5,
      series_id: "ROT-380__JKT-01",
      item_name: "Roti Sari Roti Tawar",
      location: "Jakarta Pusat",
      headline: "Review forecast confidence",
      reason: "Lumpy demand with 17 days of cover. Forecast error is above the portfolio median.",
      risk: "at_risk",
      metric_label: "Days until stockout",
      metric_value: 17,
      metric_unit: "days",
      href: "/projects/prj-abc/dashboard/supply-chain?series=ROT-380__JKT-01",
    },
  ],
};

/** GET /api/v1/value/{dataset_id} */
export const VALUE_SIMULATION: ValueSimulation = {
  dataset_id: "ds_8f21c4",
  baseline_name: "4-week moving average",
  fill_rate_baseline_percent: 91.2,
  fill_rate_model_percent: 96.8,
  stockout_events_baseline: 214,
  stockout_events_model: 78,
  avg_inventory_value_baseline: 2410000000,
  avg_inventory_value_model: 1980000000,
  net_benefit_idr: 612000000,
  window_label: "Across 2 backtest windows",
};
